### ISSUE TITLE
How to add filter

### ISSUE THREAD

**Issue by linonetwo** [bimlas/tw5-locator#5]
For example, exclude tiddlers tagged with "Task".

Seems that used to be done by using `locator-view does not supporting finalFilter and tagFilter` ?

**Comment by bimlas** [comment]
Sorry for the late reply.

Yes, it was possible to filter the list with those parameters, but they are not available since version 2.0.0 (https://bimlas.gitlab.io/tw5-locator/#%24%3A%2Fplugins%2Fbimlas%2Flocator), because I implemented the filtering with custom Javascript filters, which I used to do with filter expressions (https://github.com/bimlas/tw5-locator/commit/8139de095f75ee00e7ed8c9461aa2a7e42fd585c).

I currently have no idea how you could apply a predefined filter to the output.

**Comment by linonetwo** [comment]
Can you add a secondary filter, to filter the result?

I think it is better to be customizable.

**Comment by bimlas** [comment]
Implemented in `dev` branch of https://gitlab.com/bimlas/tw5-locator:

https://gitlab.com/bimlas/tw5-locator/-/commit/15d40a4debdeb60ac7e78a4922e002f45e0fd9b6

If you don't want to wait for the next release, you'll need to update the plugin yourself, but several things have changed in the `dev` branch compared to `master`. You can try the `dev` version at https://bimlas.gitlab.io/

**MAKE A BACKUP BEFORE UPDATING**

Since the version number has not changed in the `dev` branch, delete the plugin from your own wiki first and only then install it again, otherwise the version number will not allow you to update it.
